sudo: false
language: perl
perl:
- '5.24'
- '5.22'
- '5.20'
- '5.10'
before_install:
- git config --global user.name "TravisCI"
install:
- cpanm --quiet --notest --skip-satisfied Dist::Zilla
- cpanm --quiet --notest Task::Date::Holidays
- cpanm --quiet --notest Test::Kwalitee
- cpanm --quiet --notest Devel::Cover::Report::Coveralls
- cpanm --quiet --notest Dist::Zilla::App::Command::cover
- dzil authordeps | grep -vP '[^\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest --skip-satisfied
- dzil listdeps --author | cpanm --quiet --notest --skip-satisfied
- export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j10:c
  HARNESS_TIMER=1
- dzil listdeps | grep -vP '[^\w:]' | cpanm --quiet --notest --skip-satisfied
script:
- dzil smoke --release --author
after_success:
- dzil cover -outputdir cover_db -report coveralls
notifications:
  slack:
    secure: ObGJJc83PEMwwVc0YulauYO2GxK7p6dLDpVGantUMRieFBDKzddHpGOyqwFwj3133tSCjXhtbR4khhhhwg+zQg461GNaWmfZcsJR564BEKcoX2rzNlJitiHejjsNaYHg3IFKFsnJ0zwOBrRxdZLqZ5MzZS4TYCD05R4fvaeCrCU=
